### ISSUE TITLE
Multiple background-scripts sharing the same store

### ISSUE THREAD

**Issue by gurkerl83** [zalmoxisus/browser-redux#20]
Hi,
our setup involves multiple background-scripts depending on a single background store. I guess calling configStore in each modules entry point will generate a new store instance. The current implementation simply puts the store instance onto the window object (window.store). Defining multiple background scripts in background.html loads those scripts in a parallel fashion, consequently window.store is only available when configStore is completed. In order to resolve this issue the configurationStore and it`s internal function calls has to be adapted onto a promise based solution. Further the store initialisation has to be bundles within a shared module providing distributing the store instance on request to other modules. 

Thanks,

**Comment by zalmoxisus** [comment]
Hi! Could you please tell more about your user case? Just curious what could be the benefits of having multiple scripts while webpack can elegantly combine them.

To solve that, you may just trigger an event (let's say 'STORE_READY') [after we get the store to the global variable](https://github.com/zalmoxisus/browser-redux/blob/master/src/browser/extension/background/index.js#L7), and in all your scripts add a bind function to this event. You may make this binding as a separate module and include it in every script, so it will be easier to add more common stuff after initialization. It would work similarly to jquery's `ready` event.

Also if you do not need to persist the store (on browser reload) you may get the store synchronously. Just remove `getStoredState` from [getStateToBg](https://github.com/zalmoxisus/browser-redux/blob/master/src/app/store/getStateToBg.js) add `return store` instead of `callback(store);` and in [configureStore](https://github.com/zalmoxisus/browser-redux/blob/master/src/app/store/configureStore.js#L10) as well.

Let me know whether it works for you.

**Comment by gurkerl83** [comment]
Hi,
just wanted to tell you more about the use case of having modular content respectively background scripts. The concept is to initiate the extension with a minimal footprint handling the detection of how the extension has to respond within the current sub/domain. Ones the decision has been made a background script injects multiple content scripts into the corresponding window. Our tests show that loading our logic and window components sets at ones is not a practical approach (content scripts). Well the use case having multiple background scripts which are organised in a modular manner is just my personal preference having control about issues from our communication service. Further, modularity allows the benefit of fast testing third party code within an almost production ready software stack.

A few questions aries about webpack and organising modules. Generally within common.js you import or require a npm-module. This concept works well with modules hosted on npm and github. We have adapted the gulpfile to use browserify. Browserify has an option to expose a module name, combined with it`s option to external modules from a bundling process. This allows the import/require within another module without forcing a npm respectively git push each time a module evolves. I tried to do the same concept with webpack but its complaining module X is not available. I think I tried the declaration of a module name with the corresponding module (entry) point within browser section of package.json without any success.

Is the intended way of getting store updates within non react logic e.g. our Packagemanager still via
```store.subscribe(handleChange);``` ?

Thanks,

**Comment by zalmoxisus** [comment]
Hey,

Thanks a lot for detailed explanation, it's useful for me as I'm still thinking about best practices.

About the first question, if I understood correctly, use `npm link` for every module, after that you may add them in your project with `nmp link <module_name>`. You don't need to publish the modules to npm.

About the `store.subscribe` it's good only when you need all the states or your store data is not too complex, otherwise the operations could be too expensive as we do not have any specific information there (about the specific reducer state, which action where dispatched). Better to process the updates directly in the reducer, in a middleware, in a store enhancer or a reducer enhancer. For the most of proposes my [redux-notify](https://github.com/zalmoxisus/redux-notify) would be a good solution, as we use it for dispatching the counter from background to the content script and vice-versa.

**Comment by gurkerl83** [comment]
Hi,
one info which is quite off-topic within this thread is about crossbrowser store and notification... . There is a framework called kango-extension which handles those issues for all major browsers though a single api. Maybe it`s worth adapting browser redux for those issues. The integration with build tools such as grunt and gulp is possible spitting out either pre-packaged and fully bundled browser extensions.

Thanks,

**Comment by zalmoxisus** [comment]
Hey,
That framework is not opensource and it is not free. If you want to use it in a non opensource extension, you have to buy a commercial license. Anyway, in a month - two, Firefox deprecates the old API and you will not be able to use that framework. It worths only if you want to support IE, but it would be hard a lot to extend.
