### ISSUE TITLE
Upgrade react to 0.14

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/browser-redux#9]
I'm trying to upgrade React, but needs to be updated together Redux.

- [x] react@^0.14.0
- [x] react-dom@^0.14.0
- [x] redux@^3.0.2
- [x] react-redux@^4.0.0
- [ ] redux-devtools@^3.0.0 (waiting for release)
- [ ] redux-devtools-log-monitor@^1.0.0 (waiting for release)
- [ ] redux-devtools-dock-monitor@^1.0.0 (waiting for release)
- [x] legit-tests@^0.6.1

Wait until all released, we can begin this work. :)

**Comment by zalmoxisus** [comment]
Great! I added legit-tests in the list.

In few days I will finish splitting the project, so we will have a separate library for dealing with syncing states and another one for calling redux actions in background. That will be release 0.3, meantime I guess new redux-devtools will be released and we can update React in v0.4.

**Comment by zalmoxisus** [comment]
I delegated redux-devtools to [the another extension](https://github.com/zalmoxisus/redux-devtools-extension), so now we do not have to take here about its updates (the devtools extension should be updated automatically). Besides that, there are the following pros for a separate devtools extension:
- keep the boilerplate simple (take a look how much was [stripped](https://github.com/zalmoxisus/browser-redux/commit/f7300c1bd65afe36964c7e015ca893a14089fdb9), and added just [few lines](https://github.com/zalmoxisus/browser-redux/commit/1af01c87c7c99e4c1cc0b6bf2c4644694b7b9623) to implement).
- we may use it even for the background page.
- better debugging for the popup page in a different window or chrome devtools.

Unfortunately, due to chrome restrictions it will not work for debugging content scripts (chrome doesn't allow to include an external script here). I will think how to overcome that.

**Comment by jhen0409** [comment]
:+1: Awesome!
